version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies:ci"
    groups:
      codeql-action:
        patterns:
          - "github/codeql-action/*"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies:npm"
    open-pull-requests-limit: 10
