pre-commit:
  parallel: true
  jobs:
    - name: Check eslint
      glob: "*.{js,jsx,ts,tsx"
      run: npx eslint
      stage_fixed: true

    - name: Check tslint
      run: npx tsc
      stage_fixed: true

# For condensed output
output:
  - summary
  - failure
