name: Requesting a new feature
description: Suggesting new features to improve the project
title: 'Request: (short summary)'
labels:
  - pending treatment
  - "type: feature request"
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Description of the feature request
      description: Describe your feature request here.
      placeholder: 'Example: "I want a dark mode for the application."'
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected
      description: What is the expected result you want to see?
      placeholder: Give us a clear description of the result you want.
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Give us more informations about the feature request, like screens, logs, etc.
      placeholder: Describe the feature request with screens, logs, etc.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Contributing Guidelines](../../CONTRIBUTING.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
