name: Deploy React site to GitHub Pages

on:
  push:
    branches: [ l10n-fr, feat/react-vite ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  generate-data:
    runs-on: ubuntu-latest
    env:
      LOCALES: "en-us es fr ja ko pt-br ru zh-cn zh-tw"
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package.json

      - name: Cache logs
        id: cache-logs
        uses: actions/cache@v4
        with:
          path: history/
          key: saved-logs
          restore-keys: |
            saved-logs

      - name: Install deps
        run: npm ci

      - name: Clone MDN content repo
        if: steps.cache-logs.outputs.cache-hit != 'true'
        run: git clone --depth=1 https://github.com/mdn/content.git content

      - name: Clone MDN translated-content repo
        if: steps.cache-logs.outputs.cache-hit != 'true'
        run: git clone --depth=1 https://github.com/mdn/translated-content.git translated-content

      - name: Generate logs files
        if: steps.cache-logs.outputs.cache-hit != 'true'
        run: |
          mkdir -p history
          for locale in $LOCALES; do
            if [ "$locale" = "en-us" ]; then
              node scripts/extract-mdn-logs.cjs content en-us history/logs-en-us.txt
            else
              node scripts/extract-mdn-logs.cjs translated-content $locale history/logs-$locale.txt
            fi
          done

      - name: Generate badges
        if: steps.cache-logs.outputs.cache-hit != 'true'
        run: |
          mkdir -p public/badges
          for locale in $LOCALES; do
            if [ "$locale" != "en-us" ]; then
              node scripts/generate-badges.cjs $locale
            fi
          done

      - name: Upload data artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-data
          path: |
            history/
            public/badges/

  build:
    runs-on: ubuntu-latest
    needs: generate-data
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package.json

      - name: Install deps
        run: npm ci

      - name: Download data artifact
        uses: actions/download-artifact@v4
        with:
          name: site-data
          path: .

      - name: Build
        run: npm run build

      - name: Add 404 fallback
        run: cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
