name: Deploy React site to GitHub Pages

on:
  push:
    branches: [ l10n-fr, feat/react-vite ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate-data:
    runs-on: ubuntu-latest
    env:
      LOCALES: "en-us es fr ja ko pt-br ru zh-cn zh-tw"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Clone MDN content repo
        run: git clone --depth=1 https://github.com/mdn/content.git mdn-content

      - name: Clone MDN translated-content repo
        run: git clone --depth=1 https://github.com/mdn/translated-content.git mdn-translated

      - name: Générer logs et badges pour toutes les locales
        run: |
          mkdir -p public/history
          mkdir -p public/badges
          for locale in $LOCALES; do
            if [ "$locale" = "en-us" ]; then
              node scripts/extract-mdn-logs.cjs mdn-content en-us public/history/logs-en-us.txt
            else
              node scripts/extract-mdn-logs.cjs mdn-translated $locale public/history/logs-$locale.txt
            fi
            node scripts/generate-badges.cjs $locale
          done

      - name: Upload data artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-data
          path: |
            public/history/
            public/badges/

  build:
    runs-on: ubuntu-latest
    needs: generate-data
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package.json

      - name: Install deps
        run: npm ci

      - name: Download data artifact
        uses: actions/download-artifact@v4
        with:
          name: site-data
          path: .

      - name: Move generated data to public
        run: |
          mkdir -p public/history
          mkdir -p public/badges
          cp -r public/history/* public/history/
          cp -r public/badges/* public/badges/

      - name: Build
        run: npm run build

      - name: Add 404 fallback
        run: cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
