name: CD | Prepare merge request develop → main

on:
  push:
    branches: [ develop ]

permissions:
  contents: write
  pull-requests: write

jobs:
  open-or-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Open or update PR develop→main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -Eeuo pipefail

          git fetch --prune origin +refs/heads/*:refs/remotes/origin/*

          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD || echo "")
          if [ "$CURRENT_BRANCH" != "develop" ]; then
            git checkout -B develop
          fi

          if ! git ls-remote --exit-code origin develop >/dev/null 2>&1; then
            git push -u origin HEAD:develop
          fi

          AHEAD=$(git rev-list --left-right --count origin/main...origin/develop | awk '{print $2}')
          if [ "${AHEAD:-0}" -eq 0 ]; then
            echo "Aucun commit à proposer de develop vers main. Skip."
            exit 0
          fi

          PR_NUMBER=$(gh pr list --base main --head develop --state open --json number --jq '.[0].number // empty')
          if [ -n "${PR_NUMBER:-}" ]; then
            gh pr edit "$PR_NUMBER" --title "Release: merge develop → main" --add-label "release"
          else
            gh pr create --base main --head develop \
              --title "Release: merge develop → main" \
              --body "This pull request prepares the merge from develop to main for the next release."
          fi
