name: CD | Prepare merge request develop → main

on:
  push:
    branches: [ develop ]

permissions:
  contents: write
  pull-requests: write

jobs:
  open-or-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Open or update PR develop→main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          if gh pr list --base main --head develop --state open --json number --jq '.[0].number' >/dev/null; then
            NUM=$(gh pr list --base main --head develop --state open --json number --jq '.[0].number')
            gh pr edit "$NUM" --title "Release: merge develop → main" --add-label "release"
          else
            gh pr create --base main --head develop \
              --title "Release: merge develop → main" \
              --body "This pull request prepares the merge from develop to main for the next release."
          fi
