name: CI | Lint and validate scripts

on:
  pull_request:
    branches: ['main']
    paths:
      - '**/*.css'
      - '**/*.mjs'
      - '**/*.ts'
      - '**/*.tsx'

permissions:
  contents: read
  pull-requests: write

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f #v6.3.0
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Install reviewdog
        uses: reviewdog/action-setup@d8a7baabd7f3e8544ee4dbde3ee41d0011c3a93f #v1.5.0

      - name: Run StyleLint (via package script) and report with reviewdog
        id: stylelint_run
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run csslint | reviewdog -f=csslint -name="stylelint" -reporter=github-pr-review -level=error

      - name: Run ESLint (via package script) and report with reviewdog
        id: eslint_run
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run eslint | reviewdog -f=eslint -name="eslint" -reporter=github-pr-review -level=error

      - name: Run TypeScript check (via package script) and report with reviewdog
        id: ts_run
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run tslint | reviewdog -f=tsc -name="tsc" -reporter=github-pr-review -level=error
