name: CD | Update deployed github pages

on:
  schedule:
    - cron: "0 1,7,13,19 * * *"
      timezone: "Europe/Paris"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e #v6.4.0
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: package.json

      - name: Install deps
        run: npm ci

      - name: Clone MDN Statistics
        run: git clone --quiet https://github.com/tristantheb/history-content-stats.git stats

      - name: Getting files
        shell: bash
        run: |
          mkdir -p history statistics
          mv stats/history/* history/
          mv stats/statistics/* statistics/
          curl -fsS https://popularities.mdn.mozilla.net/current.csv -o history/current.csv
          npm run build
          cp -r history dist/history
          cp -r statistics dist/statistics
          cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 #v5.0.0
        with:
          path: dist

  # Deploy job
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 #v5.0.0
